---
mesos_playbook_version: "0.2.2"

platform_url_name: "ubuntu"
package_type: "deb"

mesos_install_mode: "master" # {master|slave|master-slave}

# exec info
mesos_bin_name: mesos
mesos_local_bin: "{{mesos_bin_name}}-local"
mesos_master_bin: "{{mesos_bin_name}}-master"
mesos_slave_bin: "{{mesos_bin_name}}-slave"

# conf file settings
# Edited it for vagrant so it will pick up the proper IP address
mesos_cluster_name: "mesos_cluster"
mesos_ip: "{{ansible_eth1.ipv4.address}}"
mesos_local_addr: "{{ansible_eth1.ipv4.address}}" #"{{ansible_fqdn}}" # {ansible_all_ipv4_addresses[1], facter_ipaddress_eth1, etc...}
mesos_local_port: "2181"
mesos_log_location: "/var/log/mesos"
mesos_ulimit: "-n 8192"
mesos_zookeepers: "zk://192.168.50.30:2181/mesos" # currently hardcoded for demo purposes. should be auto discovered. zk://{{mesos_local_addr}}:{{mesos_local_port}}/mesos" # used by masters to find zookeeper
mesos_masters: "zk://{{mesos_local_addr}}:{{mesos_local_port}}/mesos" # used by slaves
mesos_options: "--log_dir=$LOGS"
